### PR TITLE
Calc properties

### PR DESCRIPTION
**Pull request by stijnvanhoey**
Adds the `rtr`, `vid` and `vif` derived properties to the calculation.

### CODE REVIEW

**Comment by stijnvanhoey** [comment]
@peterdesmet do not merge this already, need an additionall check to compare it with the R-version output.

**Comment by peterdesmet** [comment]
@stijnvanhoey:

> do not merge this already, need an additionall check to compare it with the R-version output.

What do you want to check? Maybe I can do it?

**Comment by stijnvanhoey** [comment]
@peterdesmet I did not yet do a thoroughly comparison on the output of Biorad versus the javascript version on each of the calculated properties (I only did the mtr). I actually would write javascript unit tests to check the outcome.

Hence, for a given dataset (example data biorad):
- calculate the properties in R with biorad -> save the output
- calculate the properties with javasrcript
- assert that the outcome of js is the same as the saved output in a unit test

**Comment by peterdesmet** [comment]
Closing this PR, this is now implemented by @niconoe, but he used part of your code 😉 :

https://github.com/inbo/crow/blob/aac7416da90b2dfddb4adb4132370caa533609e3/src/helpers.ts#L168-L234

**Pull request closed without merging**
